In [2]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [4]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))
# print(my_arr)
# print(my_list)

In [5]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

314 μs ± 8.37 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
40.8 ms ± 2.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [7]:
data * 10
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [7]:
data.shape
data.dtype

dtype('float64')

In [8]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim
arr2.shape

(2, 4)

In [11]:
arr1.dtype
arr2.dtype

dtype('int64')

In [12]:
np.zeros(10)
np.zeros((3, 6))
np.empty((2, 3, 2))

array([[[5.3108e-310, 0.0000e+000],
        [5.2856e+180, 1.1328e+277],
        [6.6070e+265, 2.4512e+198]],

       [[2.4507e+198, 1.2191e-152],
        [1.1328e+277, 4.6396e+199],
        [9.0837e+223, 2.6255e-027]]])

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

dtype('int32')

In [15]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr
float_arr.dtype

dtype('float64')

In [16]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [17]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=str)
print(numeric_strings)
numeric_strings.astype(float)

['1.25' '-9.6' '42']


array([ 1.25, -9.6 , 42.  ])

In [3]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [5]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
1 / arr
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [7]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])